# @package _global_

defaults:
  - dreamer_v3_mod
  - override /algo: dreamer_v3_M_mod
  - override /env: UAVenv
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 1
  id: uav

# Checkpoint
checkpoint:
  every: 10000

# Buffer
buffer:
  size: 500000
  checkpoint: True
  memmap: True

# Algorithm
algo:
  total_steps: 90000
  cnn_keys:
    encoder: [density_matrix]
    decoder: ${algo.cnn_keys.encoder}
  mlp_keys:
    encoder: []
    decoder: ${algo.mlp_keys.encoder}
  learning_starts: 128
  

# Metric
metric:
  log_every: 5000
